### PR TITLE
Fixed code styling according to PEP8 rules.

### PR DESCRIPTION
**Pull request by zorroblue**
I used this awesome tool called pep8. I ignored the lines where you had >79 chars( The difference was atmax 5-6 characters extra).
This PR is kind of trivial. But yeah.

### CODE REVIEW

**Comment by kshitij10496** [comment]
@zorroblue LGTM

Can you add coding style fixes in the entire repo and merge them onto a single commit ?

**Comment by zorroblue** [comment]
Yeah. I'll do that

**Comment by zorroblue** [comment]
Here you go!

**Comment by kshitij10496** [comment]
Thanks !
Merged

**Pull request merged**
